=== IIIArfaoui/freevial/databases/freevial-database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="ca">
			Fitxer de preguntes i respostes per a una categoria de
			preguntes del joc freevial.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="database" type="databaseType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Element principal, a l'arrel del fitxer.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:complexType name="databaseType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Dades de la categoria.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="informationType" name="information" />
			<xs:element type="appearanceType" name="appearance" />
			<xs:element type="questionsType" name="questions" />
		</xs:sequence>
		<xs:attribute name="version" use="required" type="version">
			<xs:annotation>
				<xs:documentation xml:lang="ca">
					Format d'aquest fitxer de categoria, en previsió de
					futurs canvis. El programa actualment comprova que
					la versió del fitxer de categories sigui 1.0.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="id" use="optional">
			<xs:annotation>
				<xs:documentation xml:lang="ca">
					Nom de la categoria. Sovint coincideix amb el nom
					del fitxer sense directoris ni extensió. Totes les
					catagories que he vist en porten. Però crec que no
					es fa servir per a res.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute type="xs:string" name="language" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="ca">
					Nom del llenguatge natural en què s'han escrit les
					preguntes i respostes (per arà sempre és "català").
					El valor es mostra directament a la fitxa de la
					categoria al selector de categories, i per tant és
					el nom de la llengua, no el codi ISO (però llavors
					què passarà quan es tradueixi el freevial a altres
					llengües?). Proposo posar el nom de la llengua en la
					pròpia llengua ("català", "English", "Deustch",
					"occitan", "français"...) , donat que no veig cap
					sistema muntat per internacionalitzar aquest text.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:simpleType name="version">
		<xs:restriction base="xs:token">
			<xs:enumeration value="1.0" />
			<xs:enumeration value="1.1" >
                		<xs:annotation>
			<xs:documentation xml:lang="ca">
			   Afegeix respostes ilimitades, i media per a imatges o so a cada pregunta.	
			</xs:documentation>
		</xs:annotation>
                			
			</xs:enumeration>
			<!--	<xs:enumeration value="1,1" />  vols dir que no és un error a imatginarium.xml ??? 
				No hauria de ser tot amb punts o tot amb comes i no 1.0, 1,1 ? -->
			<xs:enumeration value="1.2" >
                		<xs:annotation>
			<xs:documentation xml:lang="ca">
			   Afegeix nivells de dificultat.	
			</xs:documentation>
		</xs:annotation>
                			
			</xs:enumeration>

		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="questionsType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Llista de preguntes de la categoria amb les
				corresponents respostes possibles.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="questionType" name="question"
				maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="relativeFilePath">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Nom de fitxer, relatiu al directori que toca.
			</xs:documentation>
		</xs:annotation>

		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>


	<xs:complexType name="appearanceType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Continguts multimèdia associats a la categoria.
			</xs:documentation>
		</xs:annotation>

		<xs:sequence>
			<xs:element name="image" type="relativeFilePath">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Nom del fitxer d'imatge (mida 1024x768 ?), camí
						relatiu al directori data/images. Imatge que es
						posa de fons a les preguntes de la categoria,
						rotant cap baix, sota una transparència que tapa
						la part de baix per escriure-hi la pregunta i
						les respostes. També surt a la dreta del
						selector de categories. Convé que sigui en blanc
						i negre (en escala de grisos) perquè se li
						aplicarà un filtre del color corresponent a la
						categoria, segons l'ordre en què s'hagi triat al
						selector de categories. Les imatges tipus
						col·lage funcionen bé en veure-les per una
						finestra estreta. Hauria d'acceptar com a mínim
						formats png, jpg,bmp i gif, excepte en sistemes
						amb una llibreria pygame rara.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="sound" type="relativeFilePath">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Nom del fitxer de so, camí relatiu al directori
						data/sounds. Ha de tenir format ogg vorbis o wav
						i una durada d'entre 2 i 5 segons
						aproximadament. És el so que sona quan la roda
						s'atura a la categoria, abans de fer cada
						pregunta de la categoria.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="authorsType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Llista d'autors i/o autores d'aquesta categoria de
				preguntes i respostes. Surt al selector de categories i
				als crèdits.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="string" name="author"
				maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure identificatiu d'un autor o autora.
						Només es mostra fins a la primera coma a la
						pantalla de selecció de categories.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="timestamp">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Data i hora expressada com a número de segons des del
				cap d'any de 1969 (inici de 1970) a Greenwich. En un
				sistema POSIX podeu obtenir el valor amb date +'%s' -d
				'2008-08-01 20:00'.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int" />
	</xs:simpleType>

	<xs:complexType name="informationType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Fitxa de la categoria de preguntes i respostes
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="string">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Nom curt de la categoria. Surt al selector de
						categories, a la roda, etc.
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="description" type="string">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Descripció dels temes de les preguntes i
						respostes. Surt al selector de categories.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="destination" type="string">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Caracterització de les persones a qui es
						recomana jugar amb aquesta categoria de
						preguntes. Per a qui s'han pensat les preguntes.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="timestamp_creation" type="timestamp">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Data i hora de la creació de la BD. En realitat
						no es fa servir per a res. Data i hora
						expressada com a número de segons des del cap
						d'any de 1969 (inici de 1970) a Greenwich. En un
						sistema POSIX podeu obtenir el valor amb date
						+'%s' -d '2008-08-01 20:00'.

					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timestamp_modification"
				type="timestamp">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Data i hora de la darrera modificació de la BD.
						Tampoc és que tingui gaire fe que aquesta dada
						es mantingui acualitzada manualment, la gent
						tendeix a descuidar-se'n, però vaja... En
						realitat no es fa servir per a res. Data i hora
						expressada com a número de segons des del cap
						d'any de 1969 (inici de 1970) a Greenwich. En un
						sistema POSIX podeu obtenir el valor amb date
						+'%s' -d '2008-08-01 20:00'.

					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element type="xs:string" name="license">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure que descriu, identifica o referencia
						les condicions que posen els autors i autores
						per poder reproduir, copiar modificar, etc.
						aquesta categoria.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="url" type="xs:anyURI" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						URL d'on es pot baixar aquest fitxer.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element type="xs:string" name="contact">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Informació de contacte dels autors i/o autores,
						típicament una única adreça de correu
						electrònic.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element type="authorsType" name="authors" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="answerType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Text d'una de les respostes.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="correct"
					use="optional">
					<xs:annotation>
						<xs:documentation xml:lang="ca">
							Si l'atribut està present vol dir que
							aquesta és la resposta correcta. El valor de
							l'atribut és indiferent (normalment hi posen
							"true"). Cada pregunta ha de tenir una única
							resposta correcta.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="questionType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Dades de la pregunta i respostes.
			</xs:documentation>
		</xs:annotation>

		<xs:sequence>
			<xs:element type="string" name="sentence">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text de la pregunta.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="string" name="author">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure identificatiu de l'autor o autora de
						la pregunta. Surt quan s'escriu la pregunta en
						pantalla. La gent acostuma a posar malnoms o
						noms d'usuari.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="string" name="comments" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure informatiu del rerefons de la
						pregunta o perquè la resposta correcta és la
						correcta i les altres no. Es mostra després de
						respondre la pregunta si l'usuari o usuària
						apreta F3.
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="media" type="mediaType" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Fitxer de imatge pr mostrar al fer la pregunta o
						só per reproduir al fer-la. Pot contenir dues
						imatges, separades per | i la primera es
						mostrarà al preguntar però la segona es mostrarà
						al mostrar la resposta correcta. Imatges són
						paths relatius a data/images i el fitxer de só
						és un camí relatiu a data/sound. (nota: jo
						posaria dos atributs, no això de la |, erò de
						moment va així).
					</xs:documentation>
				</xs:annotation>


			</xs:element>
			<xs:element type="answersType" name="answers" />
		</xs:sequence>
		<xs:attribute name="difficulty" type="difficultyType" use="optional">
		    <xs:annotation>
			<xs:documentation xml:lang="ca">
			   Indica si la pregunta és fàcil, mitjaneta o díficil.	Obligatori per a versions >= 1.2.
			   A versions anteriors si no s'indica és mitjaneta.
			</xs:documentation>
		</xs:annotation>
    
		</xs:attribute>
	</xs:complexType>
	
	
	<xs:simpleType name="difficultyType">
	    <xs:annotation>
			<xs:documentation xml:lang="ca">
			   Indica si la pregunta és fàcil, mitjaneta o díficil.	
			</xs:documentation>
		</xs:annotation>
        <xs:restriction base="xs:token" >
			<xs:enumeration value="Easy" />
			<xs:enumeration value="Medium" />
			<xs:enumeration value="Hard" />

		</xs:restriction>
	</xs:simpleType>

	

	<xs:complexType name="mediaType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Fitxer de imatge pr mostrar al fer la pregunta o só per
				reproduir al fer-la. Pot contenir dues imatges,
				separades per | i la primera es mostrarà al preguntar
				però la segona es mostrarà al mostrar la resposta
				correcta. Imatges són paths relatius a data/images i el
				fitxer de só és un camí relatiu a data/sound. (nota: jo
				posaria dos atributs, no això de la |, erò de moment va
				així).
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>

			<xs:extension base="relativeFilePath">
				<xs:attribute name="type" use="required"
					type="typeOfMediaType">
					<xs:annotation>
						<xs:documentation xml:lang="ca">
							indica si és una imatge (o dues) o bé un só.
							Val image o audio
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>

		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="typeOfMediaType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				indica si és una imatge (o dues) o bé un só. Val image o
				audio
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="audio" />
			<xs:enumeration value="image" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="answersType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Llista de respostes a la pregunta. Actualment n'hi ha
				d'haver 3 i una i només una ha d'anar marcada com a
				correcta. Es mostraran a sota de la pregunta, en un
				ordre aleatori, precedides de la lletra a,b o c.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="answerType" name="answer"
				maxOccurs="unbounded" minOccurs="3" />
		</xs:sequence>
	</xs:complexType>


	<xs:simpleType name="string">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				El programa tracta cada seqüència de #, cr i lf com un
				salt de línia (i es carrega les del principi i final de
				cada element). Però la resta de caracters de control com
				tabuladors o similars es veuen com una caixeta buida
				lletja, per tant els prohibeixo.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<!-- <xs:pattern 
				value="^[^\x00-\x09\x0b\x0c\x0e-\x1f]*$">
				</xs:pattern>-->
			<xs:pattern value="(\P{Cc}|\r|\n|\t)*"></xs:pattern>
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== IIIArfaoui/freevial/databases/historia.xml
<?xml version="1.0" encoding="UTF-8"?>

<database version="1.1" id="historia" language="ca"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///usr/share/games/freevial/databases/freevial-database.xsd">

  <information>
    <name>Història</name>
    <description>Història general</description>
    <destination>Públic catalanoparlant en general</destination>
    <timestamp_creation>1221317814</timestamp_creation>
    <timestamp_modification>1221317814</timestamp_modification>

	<license>GPLv3</license>
	<url>http://www.freevial.org/bases/historia.xml</url>
	<contact>info@freevial.org</contact>

    <authors>
      <author>Nil Oriol</author>
      <author>Núria Carreras</author>
      <author>Rafael Carreras</author>
      <author>Alex Muntada</author>
    </authors>
  </information>

  <appearance>
    <image>categoria_cat.png</image>
    <sound>mov.ogg</sound>
  </appearance>

  <questions>
    <question>
      <sentence>En quin any es fa llençar la bomba atòmica a Hiroshima?</sentence>
      <author>NúriaCarreras</author>
      <comments></comments>
      <answers>
        <answer correct="true">1945</answer>
        <answer>1935</answer>
        <answer>1955</answer>
      </answers>
    </question>


    <question>
      <sentence>Durant quants es diu que va governar Gilgamesh?</sentence>
      <author>NilOriol</author>
      <comments>Segons el llistat dels reis sumeris, Gilgamesh podria correspondre a un rei històric que va governar cap el 2700 a.C.</comments>
      <answers>
        <answer correct="true">126</answer>
        <answer>35</answer>
        <answer>16</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin és l'ordre cronològic de les edats de l'home?</sentence>
      <author>CarlesOriol</author>
      <comments></comments>
      <answers>
        <answer correct="true">Pedra, bronze i ferro</answer>
        <answer>Coure, estany i pedra</answer>
        <answer>Pedra, coure i ferro</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin és l'ordre alfabètic de les edats de l'home?</sentence>
      <author>AlexMuntada</author>
      <comments>Les edats de l'home són pedra, bronze i ferro, i les havíeu de posar en ordre alfabètic, que no és igual que l'ordre cronològic ;)</comments>
      <answers>
        <answer correct="true">Bronze, ferro i pedra</answer>
        <answer>Coure, estany i pedra</answer>
        <answer>Pedra, bronze i ferro</answer>
      </answers>
    </question>


    <question>
      <sentence>Quina és la segona edat de pedra?</sentence>
      <author>NúriaCarreras</author>
      <comments></comments>
      <answers>
        <answer correct="true">Mesolític</answer>
        <answer>Paleoític</answer>
        <answer>Neolític</answer>
        <answer>Museolític</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin era l'«homo» amb major capacitat cranial?</sentence>
      <author>NilOriol</author>
      <comments></comments>
      <answers>
        <answer correct="true">Homo neanderthalensis</answer>
        <answer>Homo sapiens</answer>
        <answer>Homo rudolfensis</answer>
      </answers>
    </question>


    <question>
      <sentence>En quin segle es va produir la batalla de Las Navas de Tolosa?</sentence>
      <author>RafaelCarreras</author>
      <comments>Es va produir el 1212 entre cristians i almoades, a Las Navas de Tolosa (província de Jaén).</comments>
      <answers>
        <answer correct="true">XIII</answer>
        <answer>XIV</answer>
        <answer>XV</answer>
      </answers>
    </question>


    <question>
      <sentence>Quina arma dispara més lluny?</sentence>
      <author>NilOriol</author>
      <comments></comments>
      <answers>
        <answer correct="true">L'arc</answer>
        <answer>Ballesta</answer>
        <answer>Amdues per igual</answer>
      </answers>
    </question>


    <question>
      <sentence>Qui va crear el Regne de Mallorca?</sentence>
      <author>RafaelCarreras</author>
      <comments></comments>
      <answers>
        <answer correct="true">Jaume I el Conqueridor</answer>
        <answer>Pere el Gran </answer>
        <answer>Guifré el Pilós</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin dels invents de Leonardo da Vinci va ser més famós en el seu temps?</sentence>
      <author>NilOriol</author>
      <comments>En el seu temps, cap d'aquests invents va passar de l'estadi de disseny ni van ser utilitzats.</comments>
      <answers>
        <answer correct="true">Cap dels dos</answer>
        <answer>Carro blindat</answer>
        <answer>Ornithopter (màquina-ocell)</answer>
      </answers>
    </question>


    <question>
      <sentence>De qui és la cèlebre frase «eppur si muove»?</sentence>
      <author>NilOriol</author>
      <comments>La traducció d'aquesta frase de l'italià és «i tot i així es mou», refermant-se en què la Terra no era el centre de l'univers quan el van acusar d'heretge per dir que girava al voltant del sol.</comments>
      <answers>
        <answer correct="true">Galieu Galilei</answer>
        <answer>Nicolau Copèrnic</answer>
        <answer>Leonardo da Vinci</answer>
      </answers>
    </question>


    <question>
      <sentence>Com va defensar Arquímedes la seva ciutat de l'atac dels romans?</sentence>
      <author>NilOriol</author>
      <comments>Gairebé tot sol, va idear un sistema de miralls i lents per incendiar les veles dels vaixells enemics amb la llum solar.</comments>
      <answers>
        <answer correct="true">Amb miralls</answer>
        <answer>Amb una gran desplegament de tropes</answer>
        <answer>Amb mines explosives</answer>
      </answers>
    </question>


  </questions>
</database>

=== IIIArfaoui/freevial/databases/ca/historia.xml
<?xml version="1.0" encoding="UTF-8"?>

<database version="1.1" id="ca-history" language="ca"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///usr/share/games/freevial/databases/freevial-database.xsd">

  <information>
    <name>Història</name>
    <description>Història general</description>
    <destination>Públic catalanoparlant en general</destination>
    <timestamp_creation>1221317814</timestamp_creation>
    <timestamp_modification>1221324599</timestamp_modification>

	<license>GPLv3</license>
	<url></url>
	<contact>info@freevial.org</contact>

    <authors>
      <author>Nil Oriol</author>
      <author>Núria Carreras</author>
      <author>Rafael Carreras</author>
      <author>Alex Muntada</author>
    </authors>
  </information>

  <appearance>
    <image>categoria_cat.png</image>
    <sound>mov.ogg</sound>
  </appearance>

  <questions>
    <question>
      <sentence>En quin any es fa llençar la bomba atòmica a Hiroshima?</sentence>
      <author>NúriaCarreras</author>
      <comments></comments>
      <answers>
        <answer correct="true">1945</answer>
        <answer>1935</answer>
        <answer>1955</answer>
      </answers>
    </question>


    <question>
      <sentence>Durant quants es diu que va governar Gilgamesh?</sentence>
      <author>NilOriol</author>
      <comments>Segons el llistat dels reis sumeris, Gilgamesh podria correspondre a un rei històric que va governar cap el 2700 a.C.</comments>
      <answers>
        <answer correct="true">126</answer>
        <answer>35</answer>
        <answer>16</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin és l'ordre cronològic de les edats de l'home?</sentence>
      <author>CarlesOriol</author>
      <comments></comments>
      <answers>
        <answer correct="true">Pedra, bronze i ferro</answer>
        <answer>Coure, estany i pedra</answer>
        <answer>Pedra, coure i ferro</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin és l'ordre alfabètic de les edats de l'home?</sentence>
      <author>AlexMuntada</author>
      <comments>Les edats de l'home són pedra, bronze i ferro, i les havíeu de posar en ordre alfabètic, que no és igual que l'ordre cronològic ;)</comments>
      <answers>
        <answer correct="true">Bronze, ferro i pedra</answer>
        <answer>Coure, estany i pedra</answer>
        <answer>Pedra, bronze i ferro</answer>
      </answers>
    </question>


    <question>
      <sentence>Quina és la segona edat de pedra?</sentence>
      <author>NúriaCarreras</author>
      <comments></comments>
      <answers>
        <answer correct="true">Mesolític</answer>
        <answer>Paleoític</answer>
        <answer>Neolític</answer>
        <answer>Museolític</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin era l'«homo» amb major capacitat cranial?</sentence>
      <author>NilOriol</author>
      <comments></comments>
      <answers>
        <answer correct="true">Homo neanderthalensis</answer>
        <answer>Homo sapiens</answer>
        <answer>Homo rudolfensis</answer>
      </answers>
    </question>


    <question>
      <sentence>En quin segle es va produir la batalla de Las Navas de Tolosa?</sentence>
      <author>RafaelCarreras</author>
      <comments>Es va produir el 1212 entre cristians i almoades, a Las Navas de Tolosa (província de Jaén).</comments>
      <answers>
        <answer correct="true">XIII</answer>
        <answer>XIV</answer>
        <answer>XV</answer>
      </answers>
    </question>


    <question>
      <sentence>Quina arma dispara més lluny?</sentence>
      <author>NilOriol</author>
      <comments></comments>
      <answers>
        <answer correct="true">L'arc</answer>
        <answer>Ballesta</answer>
        <answer>Amdues per igual</answer>
      </answers>
    </question>


    <question>
      <sentence>Qui va crear el Regne de Mallorca?</sentence>
      <author>RafaelCarreras</author>
      <comments></comments>
      <answers>
        <answer correct="true">Jaume I el Conqueridor</answer>
        <answer>Pere el Gran </answer>
        <answer>Guifré el Pilós</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin dels invents de Leonardo da Vinci va ser més famós en el seu temps?</sentence>
      <author>NilOriol</author>
      <comments>En el seu temps, cap d'aquests invents va passar de l'estadi de disseny ni van ser utilitzats.</comments>
      <answers>
        <answer correct="true">Cap dels dos</answer>
        <answer>Carro blindat</answer>
        <answer>Ornithopter (màquina-ocell)</answer>
      </answers>
    </question>


    <question>
      <sentence>De qui és la cèlebre frase «eppur si muove»?</sentence>
      <author>NilOriol</author>
      <comments>La traducció d'aquesta frase de l'italià és «i tot i així es mou», refermant-se en què la Terra no era el centre de l'univers quan el van acusar d'heretge per dir que girava al voltant del sol.</comments>
      <answers>
        <answer correct="true">Galieu Galilei</answer>
        <answer>Nicolau Copèrnic</answer>
        <answer>Leonardo da Vinci</answer>
      </answers>
    </question>


    <question>
      <sentence>Com va defensar Arquímedes la seva ciutat de l'atac dels romans?</sentence>
      <author>NilOriol</author>
      <comments>Gairebé tot sol, va idear un sistema de miralls i lents per incendiar les veles dels vaixells enemics amb la llum solar.</comments>
      <answers>
        <answer correct="true">Amb miralls</answer>
        <answer>Amb una gran desplegament de tropes</answer>
        <answer>Amb mines explosives</answer>
      </answers>
    </question>


    <question>
      <sentence>Qui és conegut per l'expressió «Eureka!»?</sentence>
      <author>NilOriol</author>
      <comments>Qualsevol cos summergit en un fluid rep una força vertical ascencional igual al pes del fluid que desallotja; aquest és el principi d'Arquímedes i eureka és l'expressió que va dir quan el va descobrir en ficar-se a la banyera i veure com l'aigua sobreeixia.</comments>
      <answers>
        <answer correct="true">Arquímedes</answer>
        <answer>Aristòtil</answer>
        <answer>Aristòfanes</answer>
      </answers>
    </question>


    <question>
      <sentence>Quin general rus va derrotar a Napoleó i a Hitler?</sentence>
      <author>NilOriol</author>
      <comments>Ni les tropes de Napoleó ni les de Hitler van sucumbir al rigor de l'hivern rus.</comments>
      <answers>
        <answer correct="true">El general Hivern</answer>
        <answer>El general Trotxev</answer>
        <answer>Ivà el Terrible</answer>
      </answers>
    </question>


    <question>
      <sentence>Quant de temps va durar la Inquisició Espanyola?</sentence>
      <author>NúriaCarreras</author>
      <comments>Fundada el 1478 pels Reis Catòlics i suprimida el 1820 pel rei Ferran VII, dins el període conegut com el Trienni Liberal, en el qual es va reimplantar la Constitució espanyola de 1812.</comments>
      <answers>
        <answer correct="true">1478 - 1820</answer>
        <answer>1321 - 1672</answer>
        <answer>1519 - 1729</answer>
      </answers>
    </question>


    <question>
      <sentence>La llei del Talió és...</sentence>
      <author>NilOriol</author>
      <comments>La frase més coneguda de la llei del Talió és «ull per ull i dent per dent».</comments>
      <answers>
        <answer correct="true">una llei de venjança limitada.</answer>
        <answer>una llei de venjança lliure.</answer>
        <answer>la pena de mort.</answer>
      </answers>
    </question>


  </questions>
</database>
