=== IIIArfaoui/freevial/databases/freevial-database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="ca">
			Fitxer de preguntes i respostes per a una categoria de
			preguntes del joc freevial.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="database" type="databaseType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Element principal, a l'arrel del fitxer.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:complexType name="databaseType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Dades de la categoria.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="informationType" name="information" />
			<xs:element type="appearanceType" name="appearance" />
			<xs:element type="questionsType" name="questions" />
		</xs:sequence>
		<xs:attribute name="version" use="required" type="version">
			<xs:annotation>
				<xs:documentation xml:lang="ca">
					Format d'aquest fitxer de categoria, en previsió de
					futurs canvis. El programa actualment comprova que
					la versió del fitxer de categories sigui 1.0.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="id" use="optional">
			<xs:annotation>
				<xs:documentation xml:lang="ca">
					Nom de la categoria. Sovint coincideix amb el nom
					del fitxer sense directoris ni extensió. Totes les
					catagories que he vist en porten. Però crec que no
					es fa servir per a res.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute type="xs:string" name="language" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="ca">
					Nom del llenguatge natural en què s'han escrit les
					preguntes i respostes (per arà sempre és "català").
					El valor es mostra directament a la fitxa de la
					categoria al selector de categories, i per tant és
					el nom de la llengua, no el codi ISO (però llavors
					què passarà quan es tradueixi el freevial a altres
					llengües?). Proposo posar el nom de la llengua en la
					pròpia llengua ("català", "English", "Deustch",
					"occitan", "français"...) , donat que no veig cap
					sistema muntat per internacionalitzar aquest text.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:simpleType name="version">
		<xs:restriction base="xs:token">
			<xs:enumeration value="1.0" />
			<xs:enumeration value="1.1" >
                		<xs:annotation>
			<xs:documentation xml:lang="ca">
			   Afegeix respostes ilimitades, i media per a imatges o so a cada pregunta.	
			</xs:documentation>
		</xs:annotation>
                			
			</xs:enumeration>
			<!--	<xs:enumeration value="1,1" />  vols dir que no és un error a imatginarium.xml ??? 
				No hauria de ser tot amb punts o tot amb comes i no 1.0, 1,1 ? -->
			<xs:enumeration value="1.2" >
                		<xs:annotation>
			<xs:documentation xml:lang="ca">
			   Afegeix nivells de dificultat.	
			</xs:documentation>
		</xs:annotation>
                			
			</xs:enumeration>

		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="questionsType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Llista de preguntes de la categoria amb les
				corresponents respostes possibles.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="questionType" name="question"
				maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="relativeFilePath">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Nom de fitxer, relatiu al directori que toca.
			</xs:documentation>
		</xs:annotation>

		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>


	<xs:complexType name="appearanceType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Continguts multimèdia associats a la categoria.
			</xs:documentation>
		</xs:annotation>

		<xs:sequence>
			<xs:element name="image" type="relativeFilePath">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Nom del fitxer d'imatge (mida 1024x768 ?), camí
						relatiu al directori data/images. Imatge que es
						posa de fons a les preguntes de la categoria,
						rotant cap baix, sota una transparència que tapa
						la part de baix per escriure-hi la pregunta i
						les respostes. També surt a la dreta del
						selector de categories. Convé que sigui en blanc
						i negre (en escala de grisos) perquè se li
						aplicarà un filtre del color corresponent a la
						categoria, segons l'ordre en què s'hagi triat al
						selector de categories. Les imatges tipus
						col·lage funcionen bé en veure-les per una
						finestra estreta. Hauria d'acceptar com a mínim
						formats png, jpg,bmp i gif, excepte en sistemes
						amb una llibreria pygame rara.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="sound" type="relativeFilePath">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Nom del fitxer de so, camí relatiu al directori
						data/sounds. Ha de tenir format ogg vorbis o wav
						i una durada d'entre 2 i 5 segons
						aproximadament. És el so que sona quan la roda
						s'atura a la categoria, abans de fer cada
						pregunta de la categoria.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="authorsType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Llista d'autors i/o autores d'aquesta categoria de
				preguntes i respostes. Surt al selector de categories i
				als crèdits.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="string" name="author"
				maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure identificatiu d'un autor o autora.
						Només es mostra fins a la primera coma a la
						pantalla de selecció de categories.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="timestamp">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Data i hora expressada com a número de segons des del
				cap d'any de 1969 (inici de 1970) a Greenwich. En un
				sistema POSIX podeu obtenir el valor amb date +'%s' -d
				'2008-08-01 20:00'.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int" />
	</xs:simpleType>

	<xs:complexType name="informationType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Fitxa de la categoria de preguntes i respostes
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="string">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Nom curt de la categoria. Surt al selector de
						categories, a la roda, etc.
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="description" type="string">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Descripció dels temes de les preguntes i
						respostes. Surt al selector de categories.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="destination" type="string">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Caracterització de les persones a qui es
						recomana jugar amb aquesta categoria de
						preguntes. Per a qui s'han pensat les preguntes.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="timestamp_creation" type="timestamp">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Data i hora de la creació de la BD. En realitat
						no es fa servir per a res. Data i hora
						expressada com a número de segons des del cap
						d'any de 1969 (inici de 1970) a Greenwich. En un
						sistema POSIX podeu obtenir el valor amb date
						+'%s' -d '2008-08-01 20:00'.

					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timestamp_modification"
				type="timestamp">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Data i hora de la darrera modificació de la BD.
						Tampoc és que tingui gaire fe que aquesta dada
						es mantingui acualitzada manualment, la gent
						tendeix a descuidar-se'n, però vaja... En
						realitat no es fa servir per a res. Data i hora
						expressada com a número de segons des del cap
						d'any de 1969 (inici de 1970) a Greenwich. En un
						sistema POSIX podeu obtenir el valor amb date
						+'%s' -d '2008-08-01 20:00'.

					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element type="xs:string" name="license">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure que descriu, identifica o referencia
						les condicions que posen els autors i autores
						per poder reproduir, copiar modificar, etc.
						aquesta categoria.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="url" type="xs:anyURI" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						URL d'on es pot baixar aquest fitxer.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element type="xs:string" name="contact">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Informació de contacte dels autors i/o autores,
						típicament una única adreça de correu
						electrònic.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element type="authorsType" name="authors" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="answerType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Text d'una de les respostes.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="correct"
					use="optional">
					<xs:annotation>
						<xs:documentation xml:lang="ca">
							Si l'atribut està present vol dir que
							aquesta és la resposta correcta. El valor de
							l'atribut és indiferent (normalment hi posen
							"true"). Cada pregunta ha de tenir una única
							resposta correcta.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="questionType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Dades de la pregunta i respostes.
			</xs:documentation>
		</xs:annotation>

		<xs:sequence>
			<xs:element type="string" name="sentence">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text de la pregunta.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="string" name="author">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure identificatiu de l'autor o autora de
						la pregunta. Surt quan s'escriu la pregunta en
						pantalla. La gent acostuma a posar malnoms o
						noms d'usuari.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="string" name="comments" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Text lliure informatiu del rerefons de la
						pregunta o perquè la resposta correcta és la
						correcta i les altres no. Es mostra després de
						respondre la pregunta si l'usuari o usuària
						apreta F3.
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="media" type="mediaType" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="ca">
						Fitxer de imatge pr mostrar al fer la pregunta o
						só per reproduir al fer-la. Pot contenir dues
						imatges, separades per | i la primera es
						mostrarà al preguntar però la segona es mostrarà
						al mostrar la resposta correcta. Imatges són
						paths relatius a data/images i el fitxer de só
						és un camí relatiu a data/sound. (nota: jo
						posaria dos atributs, no això de la |, erò de
						moment va així).
					</xs:documentation>
				</xs:annotation>


			</xs:element>
			<xs:element type="answersType" name="answers" />
		</xs:sequence>
		<xs:attribute name="difficulty" type="difficultyType" use="optional">
		    <xs:annotation>
			<xs:documentation xml:lang="ca">
			   Indica si la pregunta és fàcil, mitjaneta o díficil.	Obligatori per a versions >= 1.2.
			   A versions anteriors si no s'indica és mitjaneta.
			</xs:documentation>
		</xs:annotation>
    
		</xs:attribute>
	</xs:complexType>
	
	
	<xs:simpleType name="difficultyType">
	    <xs:annotation>
			<xs:documentation xml:lang="ca">
			   Indica si la pregunta és fàcil, mitjaneta o díficil.	
			</xs:documentation>
		</xs:annotation>
        <xs:restriction base="xs:token" >
			<xs:enumeration value="Easy" />
			<xs:enumeration value="Medium" />
			<xs:enumeration value="Hard" />

		</xs:restriction>
	</xs:simpleType>

	

	<xs:complexType name="mediaType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Fitxer de imatge pr mostrar al fer la pregunta o só per
				reproduir al fer-la. Pot contenir dues imatges,
				separades per | i la primera es mostrarà al preguntar
				però la segona es mostrarà al mostrar la resposta
				correcta. Imatges són paths relatius a data/images i el
				fitxer de só és un camí relatiu a data/sound. (nota: jo
				posaria dos atributs, no això de la |, erò de moment va
				així).
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>

			<xs:extension base="relativeFilePath">
				<xs:attribute name="type" use="required"
					type="typeOfMediaType">
					<xs:annotation>
						<xs:documentation xml:lang="ca">
							indica si és una imatge (o dues) o bé un só.
							Val image o audio
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>

		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="typeOfMediaType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				indica si és una imatge (o dues) o bé un só. Val image o
				audio
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="audio" />
			<xs:enumeration value="image" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="answersType">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				Llista de respostes a la pregunta. Actualment n'hi ha
				d'haver 3 i una i només una ha d'anar marcada com a
				correcta. Es mostraran a sota de la pregunta, en un
				ordre aleatori, precedides de la lletra a,b o c.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="answerType" name="answer"
				maxOccurs="unbounded" minOccurs="3" />
		</xs:sequence>
	</xs:complexType>


	<xs:simpleType name="string">
		<xs:annotation>
			<xs:documentation xml:lang="ca">
				El programa tracta cada seqüència de #, cr i lf com un
				salt de línia (i es carrega les del principi i final de
				cada element). Però la resta de caracters de control com
				tabuladors o similars es veuen com una caixeta buida
				lletja, per tant els prohibeixo.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<!-- <xs:pattern 
				value="^[^\x00-\x09\x0b\x0c\x0e-\x1f]*$">
				</xs:pattern>-->
			<xs:pattern value="(\P{Cc}|\r|\n|\t)*"></xs:pattern>
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== IIIArfaoui/freevial/databases/en/ubuntu.xml
<?xml version="1.0" encoding="UTF-8"?>

<database version="1.1" id="en-ubuntu" language="en"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///usr/share/games/freevial/databases/freevial-database.xsd">

  <information>
    <name>Ubuntu</name>
    <description>Everything related to Ubuntu.</description>
    <destination>People interested in Ubuntu and everything around it.</destination>
    <timestamp_creation>1221418244</timestamp_creation>
    <timestamp_modification>1221418244</timestamp_modification>

	<license>GPLv3</license>
	<url></url>
	<contact>info@freevial.org</contact>

    <authors>
      <author>Siegfried Gevatter</author>
    </authors>
  </information>
  <appearance>
    <image>categoria2.png</image>
    <sound>c2.ogg</sound>
  </appearance>
  <questions>
    <question>
      <sentence>What is a MOTU?</sentence>
      <author>RainCT</author>
      <comments>The Masters of the Universe (MOTUs) are the brave souls who
      keep the Universe and Multiverse components of Ubuntu in shape, spending
      their time adding, maintaining, and supporting as much as possible of the
      software found in them.</comments>
      <answers>
        <answer correct="true">An Ubuntu developer</answer>
        <answer correct="true">A Master of the Universe</answer>
        <answer>An audio library</answer>
        <answer>A Multitask Operated Time Unit</answer>
      </answers>
    </question>
    <question>
      <sentence>Which IRC node hosts most Ubuntu related channels?</sentence>
      <author>RainCT</author>
      <comments>The URL irc.ubuntu.com points to irc.freenode.net.</comments>
      <answers>
        <answer correct="true">Freenode</answer>
        <answer>Quakenode</answer>
        <answer>Canonical Node</answer>
      </answers>
    </question>
    <question>
      <sentence>What's the name of Canonical's well-known Community Manager?</sentence>
      <author>RainCT</author>
      <comments></comments>
      <answers>
        <answer correct="true">Jono Bacon</answer>
        <answer>Daniel Holbach</answer>
        <answer>Jonathan Backer</answer>
        <answer>Mark Shuttleworth</answer>
        <answer>Jorge Castro</answer>
      </answers>
    </question>
    <question>
      <sentence>What do you need in order to upload packages to REVU?</sentence>
      <author>RainCT</author>
      <comments></comments>
      <answers>
        <answer correct="true">A Launchpad account and a GPG key</answer>
        <answer>Only a GPG key</answer>
        <answer>Only a SSH Key</answer>
        <answer>To be manually added to its keyring</answer>
        <answer>To be an Ubuntu Developer</answer>
      </answers>
    </question>
    <question>
      <sentence>La first LTS Ubuntu version ever published is called...</sentence>
      <author>RainCT</author>
      <comments>The first Long Term Support (LTS) version of Ubuntu is the 8.04, Hardy Heron.</comments>
      <answers>
        <answer correct="true">Hardy Heron</answer>
        <answer>Dapper Drake</answer>
        <answer>Feisty Fawn</answer>
        <answer>Gutsy Gibbon</answer>
        <answer>Intrepid Ibex</answer>
        <answer>Grumpy Groundhog</answer>
      </answers>
    </question>
    <question>
      <sentence>Which of the following takes place first?</sentence>
      <author>RainCT</author>
      <comments>See https://wiki.Ubuntu.com/ReleaseSchedule</comments>
      <answers>
        <answer correct="true">DebianImportFreeze</answer>
        <answer>KernelFreeze</answer>
        <answer>FeatureFreeze</answer>
        <answer>DocumentationStringFreeze</answer>
        <answer>ArtworkDeadlineOne</answer>
      </answers>
    </question>
    <question>
      <sentence>What's the new command which replaces "aptitude upgrade" since Gutsy?</sentence>
      <author>RainCT</author>
      <comments></comments>
      <answers>
        <answer correct="true">aptitude safe-upgrade</answer>
        <answer>aptitude dist-upgrade</answer>
        <answer>aptitude all-upgrade</answer>
        <answer>It hasn't changed</answer>
      </answers>
    </question>
    <question>
      <sentence>Which of these formats work on a default Ubuntu installation?</sentence>
      <author>RainCT</author>
      <answers>
        <answer correct="true">OGG</answer>
        <answer>MP3</answer>
        <answer>DVD</answer>
      </answers>
    </question>
  </questions>
</database>

=== IIIArfaoui/freevial/databases/buida.xml
<?xml version="1.0" encoding="UTF-8"?>

<database version="1.1" id="networking" language="ca"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///usr/share/games/freevial/databases/freevial-database.xsd">

  <information>
    <name>Nom Categoria</name>
    <description>Descripci√≥ categoria</description>
    <destination>Per a qui</destination>
    <timestamp_creation>1189202400</timestamp_creation>
    <timestamp_modification>1200139483</timestamp_modification>

	<license>GPLv3</license>
	<url>http://www.freevial.org/bases/nomcategoria.xml</url>
	<contact>info@freevial.org</contact>

    <authors>
      <author>Autor 1</author>
      <author>Autor ...</author>
    </authors>
  </information>

  <appearance>
    <image>imatge.png</image>
    <sound>so.ogg</sound>
  </appearance>

  <questions>
    <question>
      <sentence>Text de la pregunta?</sentence>
      <author>Autor </author>
      <comments>Notes al final</comments>
      <answers>
        <answer correct="true">Resposta correcta</answer>
        <answer>Resposta incorrecta</answer>
        <answer>Immediate Release Communications</answer>
      </answers>
    </question>
    <question>

  </questions>
</database>

=== IIIArfaoui/freevial/databases/ca/amer.xml
<?xml version="1.0" encoding="UTF-8"?>

<database version="1.1" id="ca-amer" language="ca"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///usr/share/games/freevial/databases/freevial-database.xsd">
	<information>
		<name>Coses d'Amer</name>
		<description>
			Preguntes sobre diversos aspectes de la vila d'Amer
		</description>
		<destination>
			Per a tots aquells que vulguin comprovar el seu grau de coneixement de la història i cultura de la vila d'Amer. Categoria creada especialment per a la festa de presentació de la Ubuntu 8.10, el 29/11/2008
		</destination>
		<timestamp_creation>1227373200</timestamp_creation>
		<timestamp_modification>1227373200</timestamp_modification>
		<license>GPLv3</license>
		<url></url>
		<contact>jordi@bttamer.org</contact>
		<authors>
			<author>Teresa Sanz Dolado</author>
			<author>Jordi Àlamo Llapart</author>
		</authors>
	</information>
	<appearance>
		<!-- FIXME: Provisional-->
		<image>categoria_cat.png</image>
		<sound>mov.ogg</sound>
	</appearance>
	<questions>
		<!--Zero or more repetitions:-->
		<question>
			<sentence>Com es diuen els Gegants d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Climent i Brígida</answer>
				<answer>Arnau i Filomena</answer>
				<answer>Climent i Roser</answer>
			</answers>
		</question>

		<question>
			<sentence>Quin és l'acte principal de la Festa Major d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">La Sardana de l'Alcalde</answer>
				<answer>La Tornaboda</answer>
				<answer>El Correfoc</answer>
			</answers>
		</question>

		<question>
			<sentence>A quina comarca pertany Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">La Selva</answer>
				<answer>Garrotxa </answer>
				<answer>Gironès</answer>
			</answers>
		</question>

		<question>
			<sentence>En quin any es van adquirir els primers Gegants d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">1880</answer>
				<answer>1957</answer>
				<answer>1910</answer>
			</answers>
		</question>

		<question>
			<sentence>Quin riu travessa Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Brugent</answer>
				<answer>Onyar</answer>
				<answer>Ter</answer>
			</answers>
		</question>

		<question>
			<sentence>En quin any un terratrèmol va destruir pràcticament el poble d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">1427</answer>
				<answer>1515</answer>
				<answer>1870</answer>
			</answers>
		</question>

		<question>
			<sentence>Com es diu la Sardana de l'Alcalde?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">La Mil·lenària</answer>
				<answer>Vila d'Amer</answer>
				<answer>Fonts d'Amer</answer>
			</answers>
		</question>

		<question>
			<sentence>Quan va passar per últim cop el tren d'Olot per Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">1969</answer>
				<answer>1971</answer>
				<answer>1973</answer>
			</answers>
		</question>

		<question>
			<sentence>Qui fou el primer Alcalde d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Antoni Conches</answer>
				<answer>Llorenç Cargol</answer>
				<answer>Isidre Pujol</answer>
			</answers>
		</question>

		<question>
			<sentence>Quin any es van posar les llambordes de la Plaça d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">1982</answer>
				<answer>1990</answer>
				<answer>1984</answer>
			</answers>
		</question>

		<question>
			<sentence>Qui fou l'últim abat del Monestir d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Joan Antoni de Llanza</answer>
				<answer>Xavier de Golobart</answer>
				<answer>Josep Puigderajols</answer>
			</answers>
		</question>

		<question>
			<sentence>De quin any és l'actual campanar d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">1900</answer>
				<answer>1890</answer>
				<answer>1939</answer>
			</answers>
		</question>

		<question>
			<sentence>Com es diu l'arbre més vell d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Roure de Can Puig</answer>
				<answer>Roure de Can Ter</answer>
				<answer>Roure de Can Fornada</answer>
			</answers>
		</question>

		<question>
			<sentence>De qui és la col·lecció permanent del Museu d'Amer (Med'A)?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Lluís Sidera i Pujolràs</answer>
				<answer>Joan Garcia i Balcells</answer>
				<answer>Maria Casas i Grau</answer>
			</answers>
		</question>

		<question>
			<sentence>Quin concurs es celebra a l'aplec de Santa Brígida?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Xiulet de Cargolina</answer>
				<answer>Llançament de Pinyol</answer>
				<answer>Fumadors de Cigars</answer>
			</answers>
		</question>

		<question>
			<sentence>Com es diu la revista d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Amera</answer>
				<answer>Amerencs</answer>
				<answer>Ter</answer>
			</answers>
		</question>

		<question>
			<sentence>Quin són els colors de l'equip de futbol d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Blau i grana</answer>
				<answer>Blau i verd</answer>
				<answer>Blau i blanc</answer>
			</answers>
		</question>

		<question>
			<sentence>Com es diu el castell d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">Castell d'Estela</answer>
				<answer>Castell de Brugent</answer>
				<answer>Castell Blanc</answer>
			</answers>
		</question>

		<question>
			<sentence>De quin any data l'Ajuntament d'Amer?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">1493</answer>
				<answer>1510</answer>
				<answer>1480</answer>
			</answers>
		</question>

		<question>
			<sentence>Com es coneix el transport públic que fa el trajecte Amer – Olot?</sentence>
			<author>Teresa</author>
			<answers>
				<answer correct="true">La Teisa</answer>
				<answer>La Garrotxina</answer>
				<answer>L'Olotina</answer>
			</answers>
		</question>
	</questions>
</database>
